/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.aquirozc.jxinputemulator;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import com.sun.jna.Native;

class LibraryTest {

    @SuppressWarnings("deprecation")
    @Test void someLibraryMethodReturnsTrue() throws Exception {

        System.setProperty("jna.library.path","C:/Users/Magdalena Carmona/Downloads");

        ViGEmClient client = (ViGEmClient) Native.loadLibrary("ViGEmClient.dll", ViGEmClient.class);

        VirtualXUSB controller = new VirtualXUSB(client);

        System.out.println(controller.getVendorID());

        while(true){

            for (XUSBButton b : XUSBButton.values()){

                if(b.flag != XUSBButton.XUSB_GAMEPAD_GUIDE.flag){
                    controller.pressButton(b.flag);
                    controller.update();
                    Thread.sleep(1000);
                    controller.releaseButton(b.flag);
                    controller.update();
                }

            }

        }
      
        //assertNotNull(controller);
      
    }
}
