/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.aquirozc.jxinputemulator;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.Iterator;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        
        try {
			Thread.sleep(10000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        
        assertTrue(true, "someLibraryMethod should return 'true'");
    }
}
